In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

In [3]:
print(arr1)

[1 2 3]


In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [5]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
arrOne = np.ones((5,5)).astype(int)

In [7]:
arrOne

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
arrZeros = np.zeros((5,2)).astype(int)

In [9]:
arrZeros

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

Using Arrange 

In [10]:
arrange_array = np.arange(0,10)

In [11]:
arrange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
linspace_array = np.linspace(0,10,5)

In [13]:
linspace_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Practise Tasks

In [14]:
arr1 = np.arange(10,21)

In [15]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr2 = np.array([[5,5,5,5],[5,5,5,5],[5,5,5,5]])

In [17]:
arr2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [18]:
arrange_array = np.arange(0,21)

In [19]:
arrange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [20]:
linspace_array = np.linspace(1,5,8)

In [21]:
linspace_array

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [22]:
arr = np.arange(1,10,2)

In [23]:
arr

array([1, 3, 5, 7, 9])