In [2]:
import numpy as np

In [3]:
arr = np.linspace(10,50,5).astype(int)

In [4]:
arr

array([10, 20, 30, 40, 50])

In [5]:
print("The Third Element of the Array :",arr[2])

The Third Element of the Array : 30


In [6]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
print("The Element at index 1*2 :",arr2d[1,2])

The Element at index 1*2 : 6


In [8]:
arr[1:4]

array([20, 30, 40])

In [9]:
arr2d[0:,2:]

array([[3],
       [6],
       [9]])

In [10]:
arr = np.arange(1,13)

In [11]:
arr = arr.reshape(3,4)

In [12]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
flattend_array = arr2d.flatten()

In [14]:
flattend_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])


In [16]:
v_stack = np.vstack((arr1,arr2))

In [17]:
v_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
h_stack = np.stack((arr1,arr2))

In [19]:
h_stack

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
arr = np.arange(1,10).reshape(3,3)

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
split_arr = np.hsplit(arr,3)

In [23]:
split_arr

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [24]:
split_arrV = np.vsplit(arr,3)

In [25]:
split_arrV

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

Practise Question

In [26]:
arr1 = np.arange(0,16).reshape(4,4)

In [27]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
# TwoCol = np.hsplit(arr1,2)
TwoCol = arr1[0:,0:2]

In [29]:
TwoCol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [30]:
arr1 = arr1.reshape(2,8)

In [31]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [32]:
arr1 = arr1.flatten()

In [33]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [35]:
v_stackArray = np.vstack((arr1,arr2))

In [36]:
v_stackArray

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
h_splittedArray = np.hsplit(v_stackArray,2)

In [38]:
h_splittedArray

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]