In [12]:
import numpy as np

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [14]:
sum_arr = arr1+arr2
sum_arr

array([5, 7, 9])

In [15]:
sub_arr = arr2-arr1
sub_arr

array([3, 3, 3])

In [16]:
mul_arr = arr1*arr2
mul_arr

array([ 4, 10, 18])

In [17]:
div_arr = arr1/arr2
div_arr

array([0.25, 0.4 , 0.5 ])

BroadCasting

In [19]:
result = arr1 + 5
result

array([6, 7, 8])

In [21]:
arr3 = np.array([[1,2,3],[4,5,6]])
result = arr1+ arr3
result

array([[2, 4, 6],
       [5, 7, 9]])

In [23]:
# Universal Functions
arr1 = np.array([1,4,9])
sq_arr = np.sqrt(arr1)
sq_arr 

array([1., 2., 3.])

In [25]:
exp_arr = np.exp(arr1)
exp_arr

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [27]:
log_arr = np.log(arr1)
log_arr

array([0.        , 1.38629436, 2.19722458])

In [28]:
sin_arr,cos_arr = np.sin(arr1),np.cos(arr1)

In [29]:
sin_arr

array([ 0.84147098, -0.7568025 ,  0.41211849])

In [30]:
cos_arr

array([ 0.54030231, -0.65364362, -0.91113026])

In [31]:
# Aggregate Function 
sum = np.sum(arr1)

In [33]:
mean = np.mean(arr1)

In [34]:
sd = np.std(arr1)

In [35]:
min = np.min(arr1)

In [36]:
max = np.max(arr1)

In [37]:
print("Sum : {} \nMean : {}\nStandart Deviation : {}\nMin : {}\nMax : {}".format(sum,mean,sd,min,max))

Sum : 14 
Mean : 4.666666666666667
Standart Deviation : 3.2998316455372216
Min : 1
Max : 9


In [39]:
# Practise Questions 

In [40]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [41]:
add_arr = arr1+arr2
sub_arr = arr2-arr1
mul_arr = arr1*arr2
div_arr = arr1/arr2

In [43]:
print("Addtion : {}\n\nSubstration : {}\n\nMultiplication : {}\n\nDivision : {}".format(add_arr,sub_arr,mul_arr,div_arr))

Addtion : [[ 8 10 12]
 [14 16 18]]

Substration : [[6 6 6]
 [6 6 6]]

Multiplication : [[ 7 16 27]
 [40 55 72]]

Division : [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [44]:
arr1D = np.array([5,5,5])

In [47]:
broadCastArr = arr1D + arr2

In [48]:
broadCastArr

array([[12, 13, 14],
       [15, 16, 17]])

In [49]:
sum = np.sum(arr1)
mean = np.mean(arr1)
std = np.std(arr1)

In [50]:
print("Sum : {} \nMean : {}\nStandart Deviation : {}".format(sum,mean,sd))

Sum : 21 
Mean : 3.5
Standart Deviation : 3.2998316455372216
