In [1]:
import numpy as np

In [2]:
# Linear Algebra Operations 

In [6]:
vec1 = np.array([1,2])
vec2 = np.array([3,4])
dot_product = np.dot(vec1,vec2)
print("Dot Product of the {} and {} is : {}".format(vec1,vec2,dot_product))

Dot Product of the [1 2] and [3 4] is : 11


In [7]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
mat_multiplication = np.dot(mat1,mat2)
print("Matrix Multiplication product is : {}".format(mat_multiplication))

Matrix Multiplication product is : [[19 22]
 [43 50]]


In [8]:
mat1

array([[1, 2],
       [3, 4]])

In [10]:
mat_inv = np.linalg.inv(mat1)
mat_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [13]:
mat_det = np.linalg.det(mat1)
print("Matrix Determinant : {}".format(mat_det))

Matrix Determinant : -2.0000000000000004


In [15]:
eig_val,eig_vecs = np.linalg.eig(mat1)
print("Eigen values :",eig_val)
print("Eigen Vector :",eig_vecs)

Eigen values : [-0.37228132  5.37228132]
Eigen Vector : [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [16]:
# Random Number Generation 

In [18]:
rand_int = np.random.randint(1,10)
rand_int

8

In [20]:
rand_int_arr = np.random.randint(1,10,size=(3,3))
rand_int_arr

array([[9, 1, 4],
       [5, 6, 2],
       [4, 9, 2]], dtype=int32)

In [24]:
rand_Float_arr = np.random.rand(1,10)
rand_Float_arr

array([[1.16909610e-01, 5.32669553e-01, 6.81028239e-01, 4.47312574e-04,
        6.10084420e-01, 8.05413686e-01, 4.39374103e-01, 4.43665433e-01,
        4.14198163e-02, 4.09730898e-01]])

In [29]:
arr = np.arange(10,110,10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [47]:
rand_arr = np.random.choice(arr,5)
rand_arr

array([ 40,  20,  70, 100,  70])

In [48]:
# Practise Questions

In [54]:
rand_int_arr = np.random.randint(10,20,size=(1,10))

In [55]:
rand_int_arr

array([[17, 18, 14, 11, 15, 17, 10, 14, 19, 17]], dtype=int32)

In [56]:
mean = np.mean(rand_int_arr)
std = np.std(rand_int_arr)

In [57]:
print("Mean : {}\nStandard Deviation : {}".format(mean,std))

Mean : 15.2
Standard Deviation : 2.8213471959331766
