In [1]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])
indices = [1,2,4]
selected_el = arr[indices]
print(selected_el)

[20 30 50]


In [6]:
arr2D = np.arange(1,21).reshape(4,5)
row = [0,1,3]
col = [1,3,4]
selected2D_el = arr2D[row,col]
print(selected2D_el)

[ 2  9 20]


In [12]:
mask = arr2D%2==0
print(arr2D[mask])

[ 2  4  6  8 10 12 14 16 18 20]


In [13]:
arr = np.random.randint(1,20,size=(5,5))

In [14]:
arr

array([[ 8,  4,  2, 14,  3],
       [ 8,  4,  1,  3,  5],
       [13, 19, 17,  7,  1],
       [ 6, 19,  7,  6,  6],
       [13, 15, 16,  3, 16]], dtype=int32)

In [17]:
sorted_arr = np.sort(arr,axis=0)
sorted_arr

array([[ 6,  4,  1,  3,  1],
       [ 8,  4,  2,  3,  3],
       [ 8, 15,  7,  6,  5],
       [13, 19, 16,  7,  6],
       [13, 19, 17, 14, 16]], dtype=int32)

In [18]:
indices = np.where(arr==3)

In [19]:
indices

(array([0, 1, 4]), array([4, 3, 3]))

In [20]:
arr[indices]

array([3, 3, 3], dtype=int32)