In [1]:
import numpy as np

In [2]:
dtype = [('name','S10'),('age','i4'),('weight','f4')]
data = [
    ('Alice',22,55.5),
    ('Bob',31,70.2),
    ('Charlie',29,60)
]

In [4]:
arr = np.array(data,dtype=dtype)

In [5]:
print(arr)

[(b'Alice', 22, 55.5) (b'Bob', 31, 70.2) (b'Charlie', 29, 60. )]


In [6]:
arr['name']

array([b'Alice', b'Bob', b'Charlie'], dtype='|S10')

In [7]:
np.sort(arr,order='age')

array([(b'Alice', 22, 55.5), (b'Charlie', 29, 60. ), (b'Bob', 31, 70.2)],
      dtype=[('name', 'S10'), ('age', '<i4'), ('weight', '<f4')])

In [8]:
arr[arr['weight']>=60]

array([(b'Bob', 31, 70.2), (b'Charlie', 29, 60. )],
      dtype=[('name', 'S10'), ('age', '<i4'), ('weight', '<f4')])

In [15]:
arr = np.array([1,2,np.nan,4,5])

In [16]:
np.isnan(arr)

array([False, False,  True, False, False])

In [17]:
# clean_arr = arr[~np.isnan(arr)].astype(int)

In [18]:
# clean_arr

In [22]:
arr = np.nan_to_num(arr,nan=3)
arr.astype(int)

array([1, 2, 3, 4, 5])

In [26]:
p50 = np.percentile(arr,100)
p50 

np.float64(5.0)

In [27]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

corrCoef = np.corrcoef(x,y)

In [28]:
corrCoef

array([[1., 1.],
       [1., 1.]])

In [29]:
cov_matrix = np.cov(x, y)
cov_matrix

array([[  2.5,  25. ],
       [ 25. , 250. ]])