In [1]:
import numpy as np

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr2D = np.arange(0,12)
arr2D = arr2D.reshape(3,4)
arr2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr = arr+5
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr2D = 2*arr2D
arr2D

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [14]:
Row2 = arr2D[1,:]
Row2

array([16, 20, 24, 28])

In [16]:
Col3 = arr2D[:,2]
Col3

array([ 8, 24, 40])

In [20]:
r2c2 = arr2D[1:,2:]
r2c2

array([[24, 28],
       [40, 44]])